### PR TITLE
Email service

### PR DESCRIPTION
**Pull request by moficodes**
Email service done!

Post to email service with
to, from, subject, body

it will send email using sendgrid.

### CODE REVIEW

**Comment by MaxShapiro32** [comment]
@moficodes Should this be merged into a v2 development branch instead of the branch we have now which just consists of v1 development (and car rental data)?

**Comment by moficodes** [comment]
@max-shapiro32 not sure. i mean that might make most sense. it was meant for v2 and it barely has any use until we have checkouts in place. so might be better there.

**Comment by MaxShapiro32** [comment]
@moficodes Ok...let's create and move this to a v2 branch. Also, I think there should be a README for this service. Creating the README might go hand in hand with https://github.com/bee-travels/bee-travels-node/issues/49 I can also help with this too.

**Comment by MaxShapiro32** [comment]
Forgot to post it here but got this error message when attempting to run service:

> POST / 500 0.367 ms - 148
> ReferenceError: regeneratorRuntime is not defined

Might be related to this? https://github.com/babel/babel/issues/7824

**Comment by MaxShapiro32** [comment]
@moficodes This should merge into v1.1 branch

**Comment by MaxShapiro32** [comment]
New pull request is coming for v1.1 branch

**Pull request closed without merging**
