### PR TITLE
Exchange rate microservice

### PR DESCRIPTION
**Pull request by Grant-Steinfeld**
4 tests passing
Swagger Test harness page working

### CODE REVIEW

**Comment by jjasghar** [comment]
Can you squash this down? this looks like a real time work.

**Review by jjasghar — CHANGES_REQUESTED** [review]
Assuming it works it's got a +1 from me :)

**Comment by MaxShapiro32** [comment]
Reviewed and spoke to @Grant-Steinfeld about the PR. We agreed on some changes that will be made before merging.

**Comment by Grant-Steinfeld** [comment]
revising review and will open new pull request comments acknowledged

**Pull request closed without merging**
