### PR TITLE
MERGE IT MAXXXXXX NOWWWWWW

### PR DESCRIPTION
**Pull request by bourdakos1**
hurrrryyyyyy

### CODE REVIEW

**Comment by bourdakos1** [comment]
@max-shapiro32 
@MaxShapiro32

**Review by moficodes — CHANGES_REQUESTED** [review]
This is amazing! So much better than Max...

**Comment by bourdakos1** [comment]
> This is amazing! So much better than Max...

Thanks @moficodes!

You are my hero 🙌

**Comment by MaxShapiro32** [comment]
@bourdakos1 I have to npm install in `/ui` and `/ui/client`?

**Comment by bourdakos1** [comment]
yea

**Review by MaxShapiro32 — COMMENTED** [review]
See below

**Review by MaxShapiro32 — CHANGES_REQUESTED** [review]
Connect with other microservices

**Review by MaxShapiro32 — APPROVED** [review]
lgtm!

**Review by moficodes — APPROVED** [review]

**Pull request merged**
