### PR TITLE
Update frontend to take advantage of destination v2 features

### LINKED ISSUE #143: UI - Switch to using the image links in present in the destination object
The `/api/v1/destinations/:country/:city` now returns an array of images. We should use this array instead of manually creating the links to object storage on the frontend.

### PR DESCRIPTION
**Pull request by bourdakos1**
resolves https://github.com/bee-travels/bee-travels-node/issues/143

### CODE REVIEW

**Comment by MaxShapiro32** [comment]
@bourdakos1 Does the UI still work with how v1 was set up with images or was v1's API also updated to how v2 is?

**Comment by bourdakos1** [comment]
@MaxShapiro32 Destination v1 has been using the same json as v2. The ui only looks at the image list now

**Comment by bourdakos1** [comment]
The destination v1 api was also unnecessarily proxying the image to COS, but we have CORS set up so we can just use the links directly

**Review by MaxShapiro32 — APPROVED** [review]
lgtm

**Pull request merged**
